server:
  port: 9004

spring:
  application:
    name: myshop-web
  zipkin:
    base-url: http://localhost:9042
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  boot:
    admin:
      client:
        url: http://localhost:7779
  rabbitmq:
    host: 192.168.149.134
    port: 5672
    username: guest
    password: guest
    virtual-host: /

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

feign:
  circuitbreaker:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

myshop-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
